using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace com.karabaev.gameplayTags.editor.Baking
{
  internal static class ListBaker
  {
    private const string FileName = "BakedTags.cs";

    [InitializeOnLoadMethod]
    private static void RegenerateOnLoad() => Bake(TagDatabase.instance.Tags);

    public static void Bake(IReadOnlyList<EditorTag> tags)
    {
      var directory = TagSettings.instance.GeneratedCodeDirectory;
      if (directory == null)
      {
        Debug.LogWarning("Gameplay Tags: set a Generated Code Directory in Project Settings > Gameplay > Tags before tags can be used at runtime.");
        return;
      }

      var dirPath = AssetDatabase.GetAssetPath(directory);
      if (!AssetDatabase.IsValidFolder(dirPath))
      {
        Debug.LogWarning($"Gameplay Tags: '{dirPath}' is not a folder. Set a valid Generated Code Directory in Project Settings > Gameplay > Tags.");
        return;
      }

      var outputPath = $"{dirPath}/{FileName}";
      var content = BuildSource(tags, TagSettings.instance.GeneratedNamespace, TagSettings.instance.GeneratedClassName);

      if (File.Exists(outputPath) && File.ReadAllText(outputPath) == content) return;

      File.WriteAllText(outputPath, content);
      AssetDatabase.ImportAsset(outputPath);
    }

    private static string BuildSource(IReadOnlyList<EditorTag> tags, string namespaceName, string className)
    {
      var maxDepth = ComputeMaxDepth(tags);

      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated>");
      sb.AppendLine("// Regenerated automatically from Project Settings > Gameplay > Tags. Do not edit by hand.");
      sb.AppendLine("// </auto-generated>");
      sb.AppendLine("using com.karabaev.gameplayTags;");
      sb.AppendLine();
      sb.AppendLine($"namespace {namespaceName}");
      sb.AppendLine("{");
      sb.AppendLine($"  public static class {className}");
      sb.AppendLine("  {");
      sb.AppendLine($"    public const int MaxDepth = {maxDepth};");
      sb.AppendLine();
      sb.AppendLine("    public static readonly string[] All =");
      sb.AppendLine("    {");
      foreach (var name in tags.Where(t => !string.IsNullOrEmpty(t.Name)).Select(t => t.Name).OrderBy(n => n))
      {
        sb.AppendLine($"      \"{name}\",");
      }
      sb.AppendLine("    };");
      sb.AppendLine();
      sb.AppendLine("    public static void RegisterAll(TagRegistry registry)");
      sb.AppendLine("    {");
      sb.AppendLine("      foreach (var name in All) registry.Register(name);");
      sb.AppendLine("    }");
      sb.AppendLine("  }");
      sb.AppendLine("}");
      return sb.ToString();
    }

    internal static int ComputeMaxDepth(IReadOnlyList<EditorTag> tags)
    {
      var maxDepth = 0;
      foreach (var tag in tags)
      {
        if (string.IsNullOrEmpty(tag.Name)) continue;

        var depth = 0;
        foreach (var c in tag.Name)
        {
          if (c == Tag.Separator) depth++;
        }

        if (depth > maxDepth) maxDepth = depth;
      }

      return maxDepth;
    }
  }
}
